#!/usr/bin/env node

var sys = require('sys')
    , exec = require('child_process').exec;

exec("zip bmr.nw ./app/*", function(err, stdo, stde){
    if ( err ) console.log(err);

    console.log('Built package: bmr.nw');
});